FROM ubuntu

RUN apt-get update 
RUN apt-get install make 
RUN apt-get install -y --no-install-recommends build-essential g++ 

COPY deps/ raygun/deps/
COPY sampleapp_linux/main.cpp raygun/sampleapp_linux/
COPY sampleapp_linux/Makefile raygun/sampleapp_linux/

WORKDIR "/raygun/sampleapp_linux/"
RUN make